language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
env:
- EMBER_TRY_SCENARIO=ember-1.13
- EMBER_TRY_SCENARIO=ember-lts-2.4
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g bower
- npm install phantomjs-prebuilt
install:
- npm install
- bower install
script:
- ember try $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: heroku
  api_key:
    secure: BdH6VcFmNbEtLoRwjI2TPnzo9kYhld7s/QrvQgW4bI9fnOETDHdlMBfoRf4DBr0RcGyGnrKiZIAw2t2Eiln7zLjsmFONYkJ+T03DPUmMrm5KVWCqA2NybZqrK7hJWtBcKDduRIkzIFERZN7oYpcrUcyoYaFwNHTtJVrxHMyqJ8xb1VVkEqKMXvr3z/5+FdojC734l593Sb/FmSJnZzXM4Aw2TsB8nzEo6xn/8B/41dZeL/mWT0R3VmCaG0tb06rBlN2I+GpOlj9SpBmRXkyZaRuSGNGU3zSmMnRxYkTjoDIj9pGsILMM4BeAG2SYXmXxOW9cpwWPefl3olrff9HBxNxS1/FmCMBE8cjRzgpF33GwDdK+CyO1HQ51VTJ6V/cYYuQMIOtvGGr49g0cGhBghF3vpHu6BIiVaRd7/F/Hh5Zl/IEjUD9RNqfzMYMiYJQiUZcHVW2nVnRasX72+xz1kpuJbStOb3Jbw3R+6NOq3/eQmY1MkPCQrK9Yp6tvgcl3yVcDLLbgMOuHmniyfCXW5aObcyB33cEu9w3r/tV35XhUTh/UbM0Vl4fHc0pALrxVxHvc4yB+wyBkKNCOUauKAiJLblTqb/TFPt6Hl2F4cFoiQElhNc3+wGuQjFKfgEmZ6uetB0zV+XFU44KEnsgVP46lZJgMUSn7T/1khCTMFS8=
  app: ember-rx-shim-demo
  on:
    repo: mike-north/ember-rx-shim
